### PR TITLE
Delphi wrapper added (Class and Demo)

### PR DESCRIPTION
**Pull request by jkour**
I have written a wrapper for Delphi (D10.1) and a  demo project.
I have, also, created documentation for the Delphi class.

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately there were the following style issues with your Pull Request:

 * Commit: 892dad5f4c844b7c9deb69ea3becf56aabf02e7a
  * Your subject line is longer than 50 characters

Please follow [git commit message guidelines](http://chris.beams.io/posts/git-commit/) (you can use `git push -f` to update this PR).

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately there were the following style issues with your Pull Request:

 * Commit: 892dad5f4c844b7c9deb69ea3becf56aabf02e7a
  * Your subject line is longer than 50 characters

 * Commit: cc96508174dec0eedede3d794956670d6ff3f9c8
  * Your subject line is longer than 50 characters

Please follow [git commit message guidelines](http://chris.beams.io/posts/git-commit/) (you can use `git push -f` to update this PR).

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately there were the following style issues with your Pull Request:

 * Commit: 892dad5f4c844b7c9deb69ea3becf56aabf02e7a
  * Your subject line is longer than 50 characters

 * Commit: cc96508174dec0eedede3d794956670d6ff3f9c8
  * Your subject line is longer than 50 characters

Please follow [git commit message guidelines](http://chris.beams.io/posts/git-commit/) (you can use `git push -f` to update this PR).

---
This message was auto-generated by https://gitcop.com

**Comment by vslavik** [comment]
> jkour closed this 35 minutes ago

If you are this indecisive, it would be great if you wouldn’t waste other people’s time like this in the future. Make up your mind, get the code into presentable shape (GitCop’s feedback is far from the only issue here) and *then* submit a PR.

I just spent a completely pointless hour making sense of this PR and was about to comment when I noticed you closed it.

**Comment by jkour** [comment]
Well, what do you mean I am "this indecisive"?

Actually, I am not indecisive and I just saved you another hour of reviewing git commits as I realised that git was treating folder names "Wrapper" and "wrapper" differently among other things (GitCop's messages). So, instead of committing the fork and messing your repo up I made the decision to cancel the PR and start from the beginning.

As you will see when I submit the PR, your hour was not wasted as you have now reviewed most of the content. 

As a general note and having read other comments as well, let me say that you have done some great work here. Please don't forget that people put voluntarily (as you do) effort on your project to develop it. So, it would help if your comments didn't sound so critical as you may put people off. Perhaps it is a language issue but you want to sound more inviting to other developers.

Thanks.

**Comment by vslavik** [comment]
> Well, what do you mean I am "this indecisive”?

You submitted a PR and then closed it without as much as single word of explanation! 

If you had a reason, you should have commented on it so that I know what’s going on. And if you needed to finish the PR (that it wasn’t ready for submission is apparent from your continued activity in adding more commits, which sadly didn’t take GitCop’s advise to heart), that’s no reason to *close* the PR, but a reason to *update* it. And if you think it isn’t pretty (it isn’t) and needs some more work (it does), well, that’s what `git push -f` and `git rebase` are for.

> So, it would help if your comments didn't sound so critical as you may put people off. 

Oh please. You’re damn right I’m going to be critical of poor code. You might have noticed in your project-stalking that I’m not critical of high-quality PRs, but *of course* I’m going to criticize anything that needs improving. It’s my *responsibility* as a maintainer to do that, old school as it may sound to you. Code review is what PRs are *for*. 

Since you said you’re continuing to work on this, I’ll post the review comments I didn’t before. And again, please realize that I’m doing nothing more than holding your commits to the same standards that I hold mine to:

- I don’t understand the purpose of this PR to begin with. There already *are* Pascal bindings, so what is this even for?
- The commits need to be atomic, complete and explained (see the great guide linked above).
- There’s an awful lot of generated docs files in there that have no business being under git control; they also make reviewing the rest basically impossible.
- There’s already a directory for Pascal bindings and a directory for examples, please don’t create another toplevel one.
- Please name the project files meaningfully instead of using default names like “Project3” (what happened to numbers 1 and 2?) or “Unit4”.

**Comment by jkour** [comment]
Vaclav, 

Yes I should have written a comment when I closed the PR. I was not able to use the git commands to fix the problem anyway.

> Oh please. You’re damn right I’m going to be critical of poor code. 

Yes and I am with you on this and comments on poor coding are welcome. 
But you commented my actions and not my code until in the last message.
Anyway, I am not going to argue about this. After all, as you said, this is your space and you are the moderator.

Regarding your comments about the PR, here we go:

> I don’t understand the purpose of this PR to begin with. There already are Pascal bindings, so what is this even for?

The pascal bindings are written using FreePascal/Lazarus. Unfortunately, the main unit does not work in Delphi (can't be just ported). In addition, my unit follows Delphi coding conventions.  

> The commits need to be atomic, complete and explained (see the great guide linked above).

Yes, I can fix this.

> There’s an awful lot of generated docs files in there that have no business being under git control; they also make reviewing the rest basically impossible.

Yes, the doc files are a few but they are all webpages. I don't really agree that docs don't belong to version control as docs are updated according to changed to code but you make this call. Do you want me to remove the whole folder?

> There’s already a directory for Pascal bindings and a directory for examples, please don’t create another top level one.

What I did is to create a top level folder ("wrappers") to host both FreePascal/Delphi directories.
Other people can write for other languages, say Java, etc and can create folders within "wrappers" respectively.
Would you prefer to have a "delphi" folder in the root directory? 
About the "examples" directory, I didn't want to mess with your examples written in the language you developed WinSparkle. I feel that delphi examples should be under wrappers/delphi and, similarly, java examples written by someone else will be under wrappers/java/examples.
As previously, you decide what is best? Do you want me to create a delphi folder under /examples?

> Please name the project files meaningfully instead of using default names like “Project3” (what happened to numbers 1 and 2?) or “Unit4”.

Yes, will do so but for Delphi developers the numbers in this example are totally unimportant. But, I will do this.

Having said all this, may I ask whether you are still open to host a delphi wrapper?

Thanks

**Comment by vslavik** [comment]
> The pascal bindings are written using FreePascal/Lazarus. Unfortunately, the main unit does not work in Delphi (can't be just imported).
> In addition, my unit follows Delphi coding conventions.

That’s a bit too vague for my taste (and the original commit seems to indicate it’s meant for Delphi too). In any case, that’s surely something that can be fixed with an ifdef or two. As for coding conventions, why don’t you improve the existing code, then? 

Neither of these is a good reason to have *two* slightly different, but mostly duplicative, bindings for the same language.

> I don't really agree that docs don't belong to version control

Documentation *does* belong under VCS control, of course. But freaking 300 of *generated files* (including ephemeral build logs and binaries!) not so much. The source (here, the inline doc comments) does, build artifacts (generated MS HTML Help) not.

Does Delphi not extract the doc comments automatically for the user? Does it not have some button or whatnot to generate them at least? I mean, that’s what you presumably used, isn’t it?

> Would you prefer to have a "delphi" folder in the root directory? 

As I said, there’s already the `pascal` directory for Pascal bindings and that’s where this should go.

> Having said all this, may I ask whether you are still open to host a delphi wrapper?

Bindings (the traditional term for what you call “wrapper”) for other languages are important, so of course yes. But I don’t think treating Delphi as not being Pascal and having two different Pascal bindings makes sense.

**Comment by vslavik** [comment]
> If I used that unit I would have ended up with ifdefs every other line.

Sorry, but that’s bullshit. The reality is that you can write code compatible with both pretty easily and this seems to simply be a case of NIH syndrome more than anything else.

> Anyway, I will host the Delphi class in my repo.

Not big on Open Source ethos, I see, with that take-it-or-leave-it-I-am-perfect-won’t-improve-anything attitude of yours. Apparently, you treat code review as a personal insult, which is a real pity, because this could have been an actual useful contribution if done more respectfully to the existing Pascal code (inline doc comments, better Delphi compatibility to name two immediately obvious things) and you could have done some good for the project that did some good for you.

**Comment by jkour** [comment]
> If I used that unit I would have ended up with ifdefs every other line.
>> Sorry, but that’s bullshit. 

Ok.

> ... this seems to simply be a case of NIH syndrome more than anything else..

Ok, again

> Anyway, I will host the Delphi class in my repo.
>> Not big on Open Source ethos, I see, with that take-it-or-leave-it-I-am-perfect-won’t-improve-anything attitude of yours. 

How do you mean this? I am not going to host your project but only the DLL file and my class with full reference to your repo and work.  Do you find this unethical?

And what do you expect me to do since you don't want to host it in your repo? I am not saying you have to and I respect this decision. But, on the other hand, I want to make my class available to the public.

Can you not see how critical at personal level (not for the code) you are with the long dashed word you used? 

> Apparently, you treat code review as a personal insult, which is a real pity,

Seriously? As I said earlier, what annoyed me was your strong expression of your views about anything else but the code (not to mention the "bullshit" word). 
 
> because this could have been an actual useful contribution if done more respectfully to the existing Pascal code (inline doc comments, better Delphi compatibility to name two immediately obvious things) 

So now you find it a useful contribution? If and only if I used the existing pascal unit? Ok, I am not going to move mountains to convince you about the usefulness of a separate Delphi class especially if you consider I am not familiar with FreePascal/Lazarus as already explained.

> you could have done some good for the project 

I will still do by exercising the terms in your license

> that did some good for you

Indeed, and as I said before I thank you for the project. Apart from our disagreements, the project is amazing. Thanks for this.

**Comment by vslavik** [comment]
> How do you mean this?

“Ethos”, not “(un)ethical”. Responsible Open Source users appreciate the amount of time they save by giving back when a suitable opportunity arises — which it typically does whey they scratch their own itch of some sort and now have the choice of keeping the fix for themselves or doing a little bit of work to push it upstream. “Giving back” means doing a good job with a contribution and approaching it responsibly, iterating it if necessary, doing their best to get the fixes upstream so that everybody else benefits from them. Not throwing out a fly-by half-finished PR and loosing any interested if it doesn’t stick (or worse, being offended by any modicum of criticism).

> And what do you expect me to do since you don't want to host it in your repo?

You know, if you don’t want to have your personal behavior criticized, don’t dishonestly twist other’s words. I explicitly said I *do* want this PR. If I didn’t, I wouldn’t spend so much time reviewing it and trying (albeit in vain) to guide you towards a mergeable version.

> Can you not see how critical at personal level (not for the code) you are

Can you not see that I’m *right* to criticize your inappropriate behavior here? I’m calling you out on it because you need to be called out on it. Everything in a PR, including how you conduct yourself, *is* part of coding. 

> (not to mention the "bullshit" word).

Don’t make bold, provably (not to mention self-evidently) false statements like pretending that Pascal and Delphi are incompatible languages and you won’t be called out on spewing bullshit. Simple as that.

> So now you find it a useful contribution?

Again with the dishonesty — “now”? *Of course* it’s useful to have inline documentation. *Of course* it’s useful to fix any Delphi compatibility problems -- assuming there are any, that is (you started awfully vague and continued by just ignoring any technical questions, so for all I know, it’s just fine).

That doesn’t mean I will immediately merge a poorly done PR with bad commit messages that lie 80% of the time (add code and say “add documentation” etc.), duplicated source files, commit log files or even compiled binaries, though. There simply are some minimal quality standards to be have.

And FYI that’s *normal*. I can’t count the number of times I wrote a patch, found a better version while tidying it up to be ready for submission and then had to rework it all yet again because the maintainer pointed out a better solution or wanted it done differently. *That’s how good Open Source works*, people collaborate to improve the code.

> If and only if I used the existing pascal unit? 

Code duplication is bad. You didn’t present *any* (let alone solid and technical) argument for doing it like that. The little you said on the topic, i.e. that you would need to ifdef every line, is an evident untruth, which doesn’t exactly boost confidence in the necessity of it.

So yes, I won’t accept something that adds non-trivial code duplication *for no reason*. I'm also not going to disrespectfully — no, insultingly — throw away other contributors’ code *for no reason*. Duplicating code or throwing bad code away is OK, if *it’s backed by solid technical reasons*, but not without them.

> if you consider I am not familiar with FreePascal/Lazarus as already explained.

Please. “Not being familiar” with some compiler compatible with yours in no way prevents you from, or even limits in, fixing whatever mysterious Delphi-specific issues you had.

> > you could have done some good for the project
>
> I will still do by exercising the terms in your license

No, simply using it under the license without contributions is not “doing good for the project”. Nor is throwing an incompatible *fork* out there. *Contributing* to upstream would be.

That’s just a point of clarification, you’re of course well within your rights not to. Just don’t pretend it’s good for the project.

**Pull request closed without merging**
