### PR TITLE
Adding a .NET assembly to nicely interface WinSparkle.dll

### PR DESCRIPTION
**Pull request by T-Boss**
This is for Issue https://github.com/vslavik/winsparkle/issues/20

I've created the following projects in the solution:
* dotnet/AppcastTestHost - A self-hosting service in a console app for hosting the appcast RSS feed, release notes, and the release MSI files. This is just a test application for development purposes and includes versions 1.0.0, 1.1.0, and 1.2.0 of WinSparkleDotNetExample.
* dotnet/WinSparkleDotNet - A .NET library implementing the necessary pinvoke commands for the unmanaged WinSparkle library. This project is the reason for the pull request.
* dotnet/WinSparkleDotNetExample - A C# WPF application illustrating basic usage of the WinSparkleDotNet library
* dotnet/WinSparkleDotNetExampleInstaller - A WIX installer for testing installation and upgrade of the WinSparkleDotNetExample application. This is not meant to be a WIX tutorial or best practices and is just for testing the example app.

Submitting as a new pull request with commits broken down by project.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a42727b06f9b7f3284b6ec7d979977c7dcb7eed0
  * Your subject line is longer than 50 characters

Guidelines are available at http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

---
This message was auto-generated by https://gitcop.com

**Comment by vslavik** [comment]
(Contextual note: this is continuation of #54; yes, please use `git push -f` in the future.)

**Comment by vslavik** [comment]
It would be great if you paid attention to the comments added to PRs by bots. They are there for a reason and I was a bit surprised to see that the commits here still don’t follow good commit message practices that GitCop already pointed out in #54. 

Similarly, AppVeyor reported the previous PR as failing and it (unsurprisingly) reports the same here. If a PR breaks builds, that’s a rather serious problem *that must be fixed*. 

Moving on: I’m not a big fan of  a42727b — seems like overkill to me. Lots of code not directly related to WinSparkle, for very little benefit. I’ll gladly host the files at winsparkle.org to make the example functional. For debugging, you can always redirect to localhost temporarily, or host elsewhere, so including full web server with examples is a bit a too much IMHO. (This, BTW, is exactly while splitting commits logically is great: it makes it easy to pick some parts and not others, or to merge some immediately and some later.)

The examples should be in the already existing `examples` directory.

**Comment by vslavik** [comment]
I suppose it’s safe to conclude that fixes (for at least the serious, crashing bugs) are not forthcoming? What a pity, I was looking forward to merging this PR once fixed :-(

**Comment by T-Boss** [comment]
I'll get around to it, but the basic update feature is working, so it's not
a top priority for me at the moment.

**Comment by Herve-M** [comment]
@vslavik I have done the (complet) job [here](https://github.com/Herve-M/winsparkle/tree/feat-net-wrapper).
It has just 2 problems (using WinSparkle from master):
- Calling win_sparkle_cleanup block the calling app.
- Launching example without IDE make WinSparkle unable to access to web (or give this error) :/

**Comment by vslavik** [comment]
> @vslavik I have done the (complet) job here.

PR?

> It has just 2 problems 

Seems there's some debugging left to do then… Rest assured than neither of that is coming from WinSparkle itself.

**Comment by vslavik** [comment]
Closing in favor of #73.

**Pull request closed without merging**
