### PR TITLE
Added VS2017 projects.

### PR DESCRIPTION
**Pull request by raspopov**

### CODE REVIEW

**Comment by vslavik** [comment]
Projects are generated -- see the bkl files (and comments in existing files). This is not a good way to add new ones.

**Comment by raspopov** [comment]
Got this:
```
$ C:\Projects\bakefile-1.2.5.1_beta-win\bkl.exe WinSparkle.bkl
WinSparkle.bkl:19:22: warning: variable "vs2015.solutionfile" is never used
WinSparkle.bkl:102:27: warning: variable "vs2015.projectfile" is never used
3rdparty\dependencies.bkl:24:27: warning: variable "vs2015.generate-solution" is never used
3rdparty\expat.bkl:8:27: warning: variable "vs2015.generate-solution" is never used
3rdparty\expat.bkl:15:25: warning: variable "vs2015.projectfile" is never used
3rdparty\wxWidgets.bkl:8:27: warning: variable "vs2015.generate-solution" is never used
3rdparty\wxWidgets.bkl:15:25: warning: variable "vs2015.projectfile" is never used
examples\examples.bkl:6:22: warning: variable "vs2015.solutionfile" is never used
examples\examples.bkl:17:27: warning: variable "vs2015.projectfile" is never used
WinSparkle.bkl:2:39: error: variable "toolsets" (list of toolsets): expression "vs2015" is not a valid toolset value: must be one of "gnu", "gnu-osx", "gnu-suncc", "vs2003", "vs2005", "vs2008", "vs2010", "vs2012", "vs2013"
```

BTW if and after successful bkl-compilation is done we get same vs2017 project files so what a difference?

**Comment by vslavik** [comment]
> what a difference?

[Maintainability](https://en.wikipedia.org/wiki/Maintainability), of course -- unlike you, *I* have to keep all the projects up to date. This really should be self-evident.

Making a unified multi-toolset project, even not generated by bkl, is a valid solution. Using bkl is a valid solution. But just duplicating tons of files and expecting me to maintain them is no, sorry.

**Comment by raspopov** [comment]
You are right but I'm talking about current pull request only. Seems the latest bakefile 1.2.5.1 beta is not supported vs2017 and even vs2015, so how does you created a projects for vs2015 and how I can do that too?

**Pull request closed without merging**
