### PR TITLE
Add support for visiting web site instead of download.

### PR DESCRIPTION
**Pull request by joshkel**
If an RSS entry has a <link> attribute with a valid version number and has no
<enclosure>, then WinSparkle will launch a web browser to that link rather
than downloading and installing the update itself. This will make it easier to
use WinSparkle with password-protected downloads.

Closes vslavik/winsparkle#39.

### CODE REVIEW

**Comment by vslavik** [comment]
I'm done with code review nitpicking (this is overall *very* good, so really: all that above is just nitpicking).

There's one bigger issue, though, that I didn't even consider before until I tripped over `ParseVersionAttr`:  the fields that provide sparkle version information are defined for the *enclosure*. Your code interprets them on `<link>` elements too and I'm a bit uneasy about intentionally introducing spec (even if loose) deviations like that into WinSparkle.

So I did a bit of research and good news — turns out that Sparkle already supports this, via a `<sparkle:version>` element under the item. See sparkle-project/Sparkle#249  (and [the referenced mention by Andy](https://github.com/sparkle-project/Sparkle/issues/227#issuecomment-13192723)), it looks like this:
```xml
<item>
  <title>Version 1.2.4</title>
  <sparkle:releaseNotesLink>http://foo.bar/storage/downloads/macosx/release_notes_test.html</sparkle:releaseNotesLink>
  <pubDate>Mon, 28 Jan 2013 14:30:00 +0500</pubDate>
  <sparkle:version>1.2.4</sparkle:version>
  <link>http://foo.bar/download_link.html</link>
</item>
```

Could you update your patch to use the `<sparkle:version>` element (and `<sparkle:shortVersionString>` too, also supported by Sparkle) under `<item>` instead? TIA!

**Comment by joshkel** [comment]
Thanks for the feedback. I tried to search if Sparkle already did anything
like this and failed to find it, so thank you very much for the info.

I'll make this change and update my pull request.

**Comment by joshkel** [comment]
Updated. Let me know if there are any other changes you'd like to have made. Thanks.

**Comment by vslavik** [comment]
Wonderful, thanks a lot!

> I wondered about trying to consolidate the node logic in OnStartElement, OnEndElement, and OnText but wasn't sure that I should do that as part of this commit.

I can see why, this part of the code is getting increasingly messy. But it's probably not worth the effort, it would be better to rewrite it to use TinyXML or something (or even MSXML) — that would provide friendlier API than Expat for this use *and* be smaller in binary size.

**Pull request merged**
