### PR TITLE
CE changes for Winsparkle DLL

### PR DESCRIPTION
**Pull request by jaredburkeen**
UX changes, don't use caching for loading release notes, check for updates in the background.

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately there were the following style issues with your Pull Request:

 * Commit: 4b5acfb6418d395af8309bb36cd571627fed616b
  * Your subject line is longer than 50 characters

Please follow [git commit message guidelines](http://chris.beams.io/posts/git-commit/) (you can use `git push -f` to update this PR).

---
This message was auto-generated by https://gitcop.com

**Comment by vslavik** [comment]
Please don’t do this. It’s quite rude and inconsiderate to open a PR and then immediately close it without as much as a word of explanation.

**Comment by jaredburkeen** [comment]
Sorry about that, I made some custom changes to merge into a fork. I didn't intend to merge to your master.

**Comment by vslavik** [comment]
I see. Seems like some of the changes *are* something that should have been contributed upstream, though — you know, in the spirit of Open Source and giving back and all that...

**Comment by jaredburkeen** [comment]
Yes, good point. We've used Github at my company for a few years but this is the first time I've forked a project. I'll pull out the pieces that have potential for broader use and submit a new PR. Thanks!

**Pull request closed without merging**
