### PR TITLE
.NET WinSparkle library

### PR DESCRIPTION
**Pull request by T-Boss**
This is for Issue https://github.com/vslavik/winsparkle/issues/20

I've created the following projects in the solution:
* dotnet/AppcastTestHost - A self-hosting service in a console app for hosting the appcast RSS feed, release notes, and the release MSI files. This is just a test application for development purposes and includes versions 1.0.0, 1.1.0, and 1.2.0 of WinSparkleDotNetExample.
* dotnet/WinSparkleDotNet - A .NET library implementing the necessary pinvoke commands for the unmanaged WinSparkle library. This project is the reason for the pull request.
* dotnet/WinSparkleDotNetExample - A C# WPF application illustrating basic usage of the WinSparkleDotNet library
* dotnet/WinSparkleDotNetExampleInstaller - A WIX installer for testing installation and upgrade of the WinSparkleDotNetExample application. This is not meant to be a WIX tutorial or best practices and is just for testing the example app.

The only changed file from the original project is .gitignore, which now contains additional ignore statements for .NET projects.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 45d2e7b8b736ea5d55ab238486cfab68a2f1ec89
  * Your subject line is longer than 50 characters

 * Commit: e8e470e8b276bcaadb6ec41a8823d8b3c3efc514
  * Your subject line is longer than 50 characters

Guidelines are available at http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

---
This message was auto-generated by https://gitcop.com

**Comment by vslavik** [comment]
Thanks, I appreciate the contribution. I didn't review the code yet, but I have a comment about the commits in addition to what the bot said: it would be great if you could split this into logical, self-contained semantic commits: one commit for exactly one thing, and well described. For example, gitignore changes are logically part of *other* changes and make no sense on their own. OTOH the other über-commit would be much easier to review if it was split into parts. 

This PR description already lists the parts, why not organize the commits in the same way?

It's not that big deal and I'll review it all anyway, but it would be much simpler for me with better organization …

**Comment by T-Boss** [comment]
Ok, so you're just looking for four commits, one for each of the projects added to the solution? I assume you'd like the .gitignore changes included with the first project to be committed?

**Comment by TingPing** [comment]
@T-Boss FYI if you just `push -f` a branch GitHub will show the correct commits in an existing PR, you never need to open another one.

**Comment by vslavik** [comment]
> Ok, so you're just looking for four commits, one for each of the projects added to the solution? I assume you'd like the .gitignore changes included with the first project to be committed?

Not necessarily, I’m after *self-contained* commits that stand on their own. In `.gitignore` case, the commit — or commits! — that add some new files that must be ignored should add the files it introduced (and *only* those) there.

See [this great article on clean history](https://www.reviewboard.org/docs/codebase/dev/git/clean-commits/) and [here’s why](http://blog.crealytics.com/blog/2010/07/09/5-reasons-keeping-git-commits-small/).

**Pull request closed without merging**
