### PR TITLE
support xml:lang in release notes

### PR DESCRIPTION
**Pull request by HuangKBAaron**
Before the fix, winsparkle only picks the first item, not picking the right language attribute set by win_sparkle_set_lang function.

### CODE REVIEW

**Comment by vslavik** [comment]
Thanks!

Can you please update the commit message to be correct (this doesn't "fix" anything, it implements new functionality), mention that it closes #35 and make it so that it follows the usual formatting of git commit logs? (Please see https://github.com/agis-/git-style-guide — you can use `git push -f` to update this PR.)

**Comment by vslavik** [comment]
In addition to the comments above, this also breaks handling of appcasts *without* language-tagged release notes where the user code did explicitly set the language.

**Comment by HuangKBAaron** [comment]
ic. It is a quick solution in my case, I will spend sometime to make a sounded solution later.

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately there were the following style issues with your Pull Request:

 * Commit: eb7d349743328c2dcbbc6bf8249d1b8a58c6615e
  * Your subject line is longer than 50 characters

Please see https://github.com/agis-/git-style-guide (you can use `git push -f` to update this PR)

---
This message was auto-generated by https://gitcop.com

**Comment by vslavik** [comment]
> I will spend sometime to make a sounded solution later.

What about doing it sooner than what I suspect means "never"? You already spent time doing the PR (appreciated!), I spent time reviewing it (instead of just closing it as broken), WinSparkle could use some quality giving back...

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately there were the following style issues with your Pull Request:

 * Commit: eb7d349743328c2dcbbc6bf8249d1b8a58c6615e
  * Your subject line is longer than 50 characters

Please see https://github.com/agis-/git-style-guide (you can use `git push -f` to update this PR)

---
This message was auto-generated by https://gitcop.com

**Comment by HuangKBAaron** [comment]
:) i spent 30 minutes to learn lambda, here is the update.

**Comment by vslavik** [comment]
> :) i spent 30 minutes to learn lambda, here is the update.

Thanks, but unfortunately you didn't address either of the major issues: flawed language detection and the fact that it *breaks feeds that don't use xml:lang*. I simply can't merge this like this.

Also, please don't ignore the request for proper git commit messages. It's basic code hygiene and I have hard time believing you don't see how uninformative a commit message like "change approach" is.

**Comment by vslavik** [comment]
Closing this PR because the author abandoned it in half-finished state.

**Pull request closed without merging**
