### PR TITLE
remove redundant explicit pointer initializations which are incompatible with older c++ versions

### PR DESCRIPTION
**Pull request by matthiesenj**
This is necessary to build in e.g. VS2012. #138

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately there were the following style issues with your Pull Request:

 * Commit: 993f1f8382038cfa9629d9e8912b9bc0361fd0c3
  * Your subject line is longer than 50 characters

Please follow [git commit message guidelines](http://chris.beams.io/posts/git-commit/) (you can use `git push -f` to update this PR).

---
This message was auto-generated by https://gitcop.com

**Comment by Youw** [comment]
I'd add an initialization in c-tor instead.

**Comment by matthiesenj** [comment]
> I'd add an initialization in c-tor instead.

They are already initialized in their respective ctors, so the explicit member initializations are redundant.

**Comment by Youw** [comment]
Those are not _initialized_.
In BIOWrap it is _assigned_, before first usage, which, strictly, fine, but considered a bad practice in C++ world.
In DSAPub the variable is passed to some 3d-party function _uninitialised_, which may lead to undefined behavior under some circumstances.

**Comment by matthiesenj** [comment]
Ok, wrt `PEM_read_bio_DSA_PUBKEY` it seems you are right there could be a problem since the function does different things depending on if `dsa is `NULL` or not.

**Comment by matthiesenj** [comment]
@Youw better now?

**Comment by vslavik** [comment]
Thanks!

How much do you depend on using an old compiler like 2012? I hoped to start using more of modern C++, not less.

**Comment by vslavik** [comment]
Squashed in 798d11841915952f35afb17d0500460cf8feba3e together with the linkage fix you described in the other issue. Thanks!

**Comment by matthiesenj** [comment]
> 
> 
> Thanks!
> 
> How much do you depend on using an old compiler like 2012? I hoped to start using more of modern C++, not less.

I am just about to switch to VS2019, so in that respect, supporting old  compilers is not a problem.
The project clearly indicates itself (through the project files) as being buildable in older VS versions, and that I think is a problem, if that is actually not the case. That's why I mentioned in #138 that versions which are no longer maintained maybe should just be branched off, so it is clear, which VS versions are supported by the current configuration of the code :-)

**Pull request closed without merging**
