### PR TITLE
Cmake for MinGW

### PR DESCRIPTION
**Pull request by drizt**
It tested with Windows MinGW Qt 5.3.1 and Fedora MinGW.
For MSVC 2010 I can't build. Probably support for MSVC can be added. But I haven't such wishes atm.

### CODE REVIEW

**Comment by vslavik** [comment]
I’ll start by saying that having MinGW support would be nice — even though WinSparkle is buildable with free version of VS, being able to build with gcc would be welcome.

However, I take issue with the use of CMake. Using it as the only build system is out of the question (due to its requirement that all users have it installed) and maintaining two parallel build systems would be wasteful. The projects in there are already generated using [Bakefile](http://bakefile.org) and a better approach would arguably be to make its GNU makefiles backend work with MinGW, which should be pretty minor. I’m not closing this outright, but I’m not sure whether to merge it.

At the very least, it’s my understanding (see #62) that this doesn’t even work — and so is unmergeable by definition. That aside, it would be easier to live with if the CMake files weren’t all over the place and if it didn’t significantly change the imported expat code (putting one dependency in `3rdparty/CMakeLists.txt` and the other in `3rdparty/something/CMakeLists.txt` in particular makes little sense).

**Comment by drizt** [comment]
I didn't work with Bakefile. I looked at Bakefile documentaion but didn't see MinGW support. If Bakefile supports MinGW probably using of Bakefile will be the best approach.

**Comment by drizt** [comment]
I added `WX_PRECOMP` to defines. It solved compilation problem.

**Comment by vslavik** [comment]
> I added WX_PRECOMP to defines. It solved compilation problem.

Congratulations on making the build significantly slower — you really should *enable precompiled headers* as I wrote above...

**Comment by drizt** [comment]
Maybe you right. I never used precompiled headers before. It's not applied in gcc world.

**Comment by drizt** [comment]
Added procompiled headers support

**Comment by drizt** [comment]
Can't compile with latest changes. I got such error

    [ 70%] Building CXX object 3rdparty/CMakeFiles/wxWidgets.dir/wxWidgets/src/msw/dir.cpp.obj                                                                                                                                                   
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/src/msw/dir.cpp: In member function 'bool wxDirData::Read(wxString*)':
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/src/msw/dir.cpp:265:44: error: call of overloaded 'wxLogSysError(DWORD&, const wxString&, wxCStrData)' is ambiguous
                               m_dirname.c_str());
                                            ^
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/src/msw/dir.cpp:265:44: note: candidates are:
    In file included from /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/string.h:46:0,
                     from /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/log.h:43,
                     from /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/msw/private.h:23,
                     from /home/taurus/develop/winsparkle/build/3rdparty/wxprec.h:44:
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/log.h:1489:31: note: void wxLogSysError(long int, const wxFormatString&, T1) [with T1 = wxCStrData]
         WX_DEFINE_VARARG_FUNC_NOP(wxLog##level, 2, (argclass, const wxFormatString&)) \
                                   ^
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/strvararg.h:1156:10: note: in definition of macro '_WX_VARARG_DEFINE_FUNC_NOP'
         void name(_WX_VARARG_FIXED_UNUSED_EXPAND(numfixed, fixed),                \

Seems problem in `wxUSE_INTL` now is `1`. 

Here 

            wxLogSysError(err, _("Cannot enumerate files in directory '%s'"), m_dirname.c_str());

`_("Cannot enumerate files in directory '%s'")` has type wxString but `m_dirname.c_str()` is not. If use such argument ``_("Cannot enumerate files in directory '%s'")`.c_str()` it will be compiled fine.

**Comment by drizt** [comment]
Seems I found an error. I trying to compile wxWidgets (without WinSparkle) on Fedora 22. So.

    $ mingw32-configure --disable-log
    ...
    $ make -j5
    ...
    ./src/msw/dir.cpp: In member function 'bool wxDirData::Read(wxString*)':
    ./src/msw/dir.cpp:265:66: error: call of overloaded 'wxLogSysError(DWORD&, const wxString&, wxCStrData)' is ambiguous
                                                 m_dirname.c_str());


With `--enable-log` no error.

**Comment by drizt** [comment]
Fill bugreport on trac.wxwidgets.org

**Comment by vslavik** [comment]
> Fill bugreport on trac.wxwidgets.org

Please don't. This is well documented in wx's docs.

**Comment by drizt** [comment]
Too late. http://trac.wxwidgets.org/ticket/17048. Anyway in documentation I can't find topic "How to build wxWidgets.". Also any compilation error on `make` (after `./configuration`) it's not OK IMHO.

**Comment by vslavik** [comment]
Ah, you're talking about building wx itself. No idea why you add such irrelevant things here, then :(

**Comment by drizt** [comment]
Then remove this noise.

**Comment by drizt** [comment]
commit [b08ca17749ba3cdd86f83e1980a25680ee02d968](https://github.com/wxWidgets/wxWidgets/commit/b08ca17749ba3cdd86f83e1980a25680ee02d968) in wxWidgets submodule fixed compilation error. I tried to build with this commit. Now it works. Please update wxWidgets submodule.

**Comment by drizt** [comment]
I noticed you updated wxWidgets. I rebased my cmake branch to latest winsparkle source. Now all works. Can we continue this PR?

**Comment by vslavik** [comment]
> Can we continue this PR?

Please see my very first comment. Make it so that it is easy to update the Cmake files and so that they stay largely out of the way and can be ignored and I’m inclined to merge it then. Preferably be means of generating them from the same source in the first place (which I have a feeling would be less work than this), but failing that, at least by organizing them better instead of leaving these huge files full of custom code scattered inconsistently all over the place (see above).  Ideally by putting it all under `cmake/` so that I can largely ignore its existence.

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately there were the following style issues with your Pull Request:

 * Commit: b9804352c4cada83a11a5518a85ff4e0202e025d
  * Your subject line is longer than 50 characters

Please see https://github.com/agis-/git-style-guide (you can use `git push -f` to update this PR)

---
This message was auto-generated by https://gitcop.com

**Comment by drizt** [comment]
All CMake stuff moved to cmake subfolder.
Notice I edited *3rdparty/expat/ConfigureChecks.cmake*. Without such changing I can't use *ConfigureChecks.cmake* outside the *3rdparty/expat* folder.

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately there were the following style issues with your Pull Request:

 * Commit: b9804352c4cada83a11a5518a85ff4e0202e025d
  * Your subject line is longer than 50 characters

Please see https://github.com/agis-/git-style-guide (you can use `git push -f` to update this PR)

---
This message was auto-generated by https://gitcop.com

**Comment by vslavik** [comment]
> Without such changing I can't use ConfigureChecks.cmake outside the 3rdparty/expat folder.

You shouldn’t have any need or reason to use it at all in the first place: you’re not targeting all platforms Expat supports, just a single one, compiling on which is trivial, as you can observe in `expat.bkl`.

Please also see https://github.com/agis-/git-style-guide#commits about commit messages and organization, length limit is the least of it.

**Comment by drizt** [comment]
> You shouldn’t have any need or reason to use it at all in the first place: you’re not targeting all platforms 
MinGW is not Visual Studio. `expat.bkl` defines `COMPILED_FROM_DSP` which suitable for VS based projects. I can't be sure that is correct for MinGW furthermore for **any** version of MinGW. Or if/when expat will be updated meaning of `COMPILED_FROM_DSP` can be changed. `ConfigureChecks.cmake` checks environment and set defines for current system. So in this case I can be sure that it is ok. Unfortunately in this case small fix of `ConfigureChecks.cmake` is required.

**Comment by vslavik** [comment]
> I can't be sure that is correct for MinGW furthermore for any version of MinGW.

Changes are it is (given what CRT MinGW uses), but OK, that’s a fair point…

> Or if/when expat will be updated

That’s a good one. Hell will probably freeze over before that happens, even if I don’t remove this dependency sooner than that...

**Comment by drizt** [comment]
Updated commit messages. Now

**Comment by drizt** [comment]
ping

**Comment by vslavik** [comment]
> ping

FYI, the only thing you accomplish with bugging is more delays. Just don’t.

If you want this merged faster, why don’t you, instead of bugging, focus on improving it. See any git guide on the commit messages: the idea is not to fill a paragraph, but to put *useful and informative* description there. Talking about some future commits or rationale for splitting commits (i.e. git 101) is totally off-topic, so is stating the obvious that is visible from the commit itself (“all placed in cmake directory”) as opposed to explaining things (“put everything in cmake directory to interfere with the official build as little as possible”). 

On to the diff itself: I very much doubt there’s any need for that `${CUR_DIR}` everywhere (which, to make it worse, has value *that is not “current dir”* as it calls itself!). And I don’t think it makes sense to mirror the source directories tree under `cmake` — why?! Make it clean, simple and easy to use. If that requires doing things differently, argue your case. But this is a mess, there’s no rational reason to have e.g. `PCHSupport.cmake` under `3rdparty`, short of it being the simplest thing you could do.

**Comment by drizt** [comment]
Improved commit messages.

Reorganised files in cmake folder. Some folders is required becouse each CMake project must use own directory and own CMakeLists.txt file. But I reduced files hell.

Also now `CMAKE_BUILD_TYPE=Release` by default.

**Comment by vslavik** [comment]
Sorry, I apparently forgot to push my local copy :( Done now. Thanks!

**Pull request merged**
